baseURL = "https://jacakira.github.io"
publishDir = "public"
languageCode = "en-gb"
title = "Akira Tanase"
theme = "folio"
disableFastRender = true
cleanDestinationDir = true
minify = true

[params]
  math = true
  description = "Akira Tanase â€” mathematics, machine learning"
  spotifyNowPlayingEndpoint = "https://spotify-backend-alpha.vercel.app/api/spotify-now-playing"
  spotifyLastPlayedEndpoint = "https://spotify-backend-alpha.vercel.app/api/spotify-last-played"
  author = "Akira Tanase"

[params.disabledSections]
  music = true
  misc = true

[markup.highlight]
  noClasses = false
  style = "none"
  lineNos = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.extensions]
    footnote = true


